### ISSUE TITLE
confusing error when PHANTOM_PATH is bad

### ISSUE THREAD

**Issue by hexsprite** [xolvio/meteor-webdriver#29]
when I updated to newest Meteor release today I all of a sudden was getting this error from CircleCI that used PHANTOM_PATH

probably should be fixed upstream but wanted to capture it somewhere

```
W20150226-01:37:48.301(0)? (STDERR) fs.js:408
W20150226-01:37:48.301(0)? (STDERR)   return binding.close(fd);
W20150226-01:37:48.302(0)? (STDERR)                  ^
W20150226-01:37:48.303(0)? (STDERR) TypeError: Bad argument
W20150226-01:37:48.303(0)? (STDERR)   at fs.closeSync (fs.js:408:18)
W20150226-01:37:48.303(0)? (STDERR)   at Object.closeSync (/home/ubuntu/.meteor/packages/velocity_core/.0.4.5.bned78++os+web.browser+web.cordova/npm/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:114:12)
W20150226-01:37:48.303(0)? (STDERR)   at ChildProcess.<anonymous> (/home/ubuntu/amplifield/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:256:19)
W20150226-01:37:48.303(0)? (STDERR)   at ChildProcess.emit (events.js:98:17)
W20150226-01:37:48.303(0)? (STDERR)   at Process.ChildProcess._handle.onexit (child_process.js:810:12)
```

**Comment by samhatoum** [comment]
latest version uses Meteor's phantom, but the error should still be fixed I guess for custom paths
