### ISSUE TITLE
Updating to version 0.4.0. Tests works longer. Strange STDERR output.

### ISSUE THREAD

**Issue by crimsonking** [xolvio/meteor-webdriver#30]
Hi. After updating xolvio:webdriver I got strange STDERR output. And tests works slower (I'm using single mirror to execute tests). 237s for 0.4.0 and 41s for 0.3.1.
Here is STDERR output:
```
I20150302-17:48:40.255(3)? [xolvio:cucumber] Cucumber is running
W20150302-17:49:14.670(3)? (STDERR) (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
W20150302-17:49:14.671(3)? (STDERR) Trace
W20150302-17:49:14.672(3)? (STDERR)   at process.addListener (events.js:160:15)
W20150302-17:49:14.672(3)? (STDERR)   at process.on.process.addListener (node.js:773:26)
W20150302-17:49:14.672(3)? (STDERR)   at _startPhantom (/Volumes/DATA/workspace/app_folder/app/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:319:13)
W20150302-17:49:14.672(3)? (STDERR)   at /Volumes/DATA/workspace/app_folder/app/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:139:7
W20150302-17:49:14.672(3)? (STDERR)   at runWithEnvironment (/Volumes/DATA/workspace/app_folder/app/.meteor/local/build/programs/server/packages/meteor.js:1052:24)
W20150302-17:49:14.672(3)? (STDERR)
W20150302-17:49:19.855(3)? (STDERR) (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
W20150302-17:49:19.855(3)? (STDERR) Trace
W20150302-17:49:19.856(3)? (STDERR)   at process.addListener (events.js:160:15)
W20150302-17:49:19.856(3)? (STDERR)   at process.on.process.addListener (node.js:773:26)
W20150302-17:49:19.856(3)? (STDERR)   at _startPhantom (/Volumes/DATA/workspace/app_folder/app/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:311:13)
W20150302-17:49:19.856(3)? (STDERR)   at /Volumes/DATA/workspace/app_folder/app/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:139:7
W20150302-17:49:19.856(3)? (STDERR)   at runWithEnvironment (/Volumes/DATA/workspace/app_folder/app/.meteor/local/build/programs/server/packages/meteor.js:1052:24)
W20150302-17:49:19.856(3)? (STDERR)
W20150302-17:49:19.857(3)? (STDERR) (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
W20150302-17:49:19.857(3)? (STDERR) Trace
W20150302-17:49:19.857(3)? (STDERR)   at process.addListener (events.js:160:15)
W20150302-17:49:19.857(3)? (STDERR)   at process.on.process.addListener (node.js:773:26)
W20150302-17:49:19.857(3)? (STDERR)   at _startPhantom (/Volumes/DATA/workspace/app_folder/app/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:315:13)
W20150302-17:49:19.857(3)? (STDERR)   at /Volumes/DATA/workspace/app_folder/app/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:139:7
W20150302-17:49:19.857(3)? (STDERR)   at runWithEnvironment (/Volumes/DATA/workspace/app_folder/app/.meteor/local/build/programs/server/packages/meteor.js:1052:24)
W20150302-17:49:19.858(3)? (STDERR)
```

**Comment by samhatoum** [comment]
sounds like you have a missing callback somewhere in cucumber
