### ISSUE TITLE
Phantom failed to start

### ISSUE THREAD

**Issue by Sanjo** [xolvio/meteor-webdriver#31]
I get this regularily after app restarts since 0.4.0. Need to restart the app manually.

```
W20150302-17:31:10.486(1)? (STDERR) Phantom failed to start in 5  seconds /Users/jonas/.meteor/packages/meteor-tool/1.0.41/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs
W20150302-17:31:10.487(1)? (STDERR) 
W20150302-17:31:10.487(1)? (STDERR) /Users/jonas/simian/simian/apps/simian/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:287
W20150302-17:31:10.487(1)? (STDERR)       throw new Error('Phantom failed to start');                             
W20150302-17:31:10.487(1)? (STDERR)             ^
W20150302-17:31:10.487(1)? (STDERR) Error: Phantom failed to start
W20150302-17:31:10.487(1)? (STDERR)   at [object Object]._onTimeout (/Users/jonas/simian/simian/apps/simian/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:287:13)
W20150302-17:31:10.487(1)? (STDERR)   at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
W20150302-17:31:10.488(1)? (STDERR) 

```

**Comment by hexsprite** [comment]
+1 at the very least it shouldn't crash the entire app, just not run the tests...

**Comment by hexsprite** [comment]
it's not starting because there's no port provided to the phantomjs invocation.

I got it working by adding this to `wdio.getGhostDriver`:

```
    options = _.defaults(options, defaultOptions);
```

**Comment by samhatoum** [comment]
Oops! Thanks for investigating. 

@hexsprite want me to add you as a contributor to this and the cukes repos?

**Comment by samhatoum** [comment]
fixes in latest

**Comment by stlouisweb** [comment]
I'm getting this same error now
