### ISSUE TITLE
before is not defined

### ISSUE THREAD

**Issue by marcusreese** [xolvio/meteor-webdriver#39]
I'm new at this. I added coffeescript (because it's listed in atmosphere as a dependency, but I'm probably misunderstanding that) and then xolvio:webdriver and then pasted your starter code in a .js file in tests/jasmine/server/unit/e2e/ 
but I get:
ReferenceError: before is not defined
    at Suite.<anonymous> (/Users/marcusreese/Projects/swen/swen/tests/jasmine/server/unit/e2e/e2eBrowse.js:5:3)
    at addSpecsToSuite (/Users/marcusreese/.meteor/packages/sanjo_jasmine/.0.14.0.1x6lgms++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:685:25)
    at Env.describe (/Users/marcusreese/.meteor/packages/sanjo_jasmine/.0.14.0.1x6lgms++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:655:7)
    at jasmineInterface.describe (/Users/marcusreese/.meteor/packages/sanjo_jasmine/.0.14.0.1x6lgms++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2829:18)
    at /Users/marcusreese/Projects/swen/swen/tests/jasmine/server/unit/e2e/e2eBrowse.js:1:1
    at runFileInContext (/Users/marcusreese/Projects/swen/swen/.meteor/local/build/programs/server/packages/sanjo_jasmine.js:727:10)
    at Object.loadFile (/Users/marcusreese/Projects/swen/swen/.meteor/local/build/programs/server/packages/sanjo_jasmine.js:958:7)
    at executeSpecsUnitMode [as runTests]\ (/Users/marcusreese/Projects/swen/swen/.meteor/local/build/programs/server/packages/sanjo_jasmine.js:1473:18)
    at runWithEnvironment (/Users/marcusreese/Projects/swen/swen/.meteor/local/build/programs/server/packages/meteor.js:1041:24)

Marcuss-MacBook-Pro:swen marcusreese$ meteor list
angular:angular-material     0.10.0  Google Material design written for Angul...
angular:angular-mocks        1.4.0* AngularJS (official) release. For full so...
angularui:angular-ui-router  0.2.15  angular-ui-router (official): Flexible r...
coffeescript                 1.0.6  Javascript dialect with fewer braces and ...
insecure                     1.0.3  Allow all database writes by default
meteor-platform              1.2.2  Include a standard set of Meteor packages...
meteorhacks:fast-render      2.5.0* Render your app before the DDP connection...
sanjo:jasmine                0.14.0* Easily use Jasmine in Meteor
urigo:angular                0.9.0* The simplest no-conflict way to use Angul...
velocity:html-reporter       0.6.2* Reactive Velocity test reports in your app.
xolvio:webdriver             0.5.2  Webdriver.io for Meteor

github.com/marcusreese/swen

**Comment by marcusreese** [comment]
https://github.com/Sanjo/meteor-jasmine/wiki/End-to-End-Tests 
uses <code>beforeEach</code> whereas 
https://atmospherejs.com/xolvio/webdriver
and
https://github.com/xolvio/meteor-webdriver
use <code>before</code>.
The one in the wiki (beforeEach) works for me, so I'm done, but does the github and atmosphere readme example need to be fixed?
Thanks for your work!

P.S. The current (working) code from the wiki is:
```
describe('Browser testing', function() {

  var browser;

  beforeEach(function (done) {
    wdio.getGhostDriver(function(_browser_) {
      browser = _browser_;
      done();
    });
  });

  it('should have the correct title', function (done) {
    browser
      .init()
      .url('http://www.google.com')
      .title(function(err, res) {
        console.log('Title was: ' + res.value);
        expect(res.value).toBe('Google');
      })
      .end()
      .call(done);
  });
});
```

**Comment by Sanjo** [comment]
I think the example in the README is for Mocha. I will add a note for that and reference to the example for Jasmine.

**Comment by Sanjo** [comment]
Fixed with https://github.com/xolvio/meteor-webdriver/commit/bd3dbbcdedbc1f55d93a1bc7e83d9a1b54e866ca

**Comment by marcusreese** [comment]
Thanks!

**Comment by Sanjo** [comment]
@marcusreese I have changed the example to use beforeAll. So that the ghost driver is only created before all tests once. https://github.com/Sanjo/meteor-jasmine/wiki/End-to-End-Tests

**Comment by marcusreese** [comment]
Helpful!
