### ISSUE TITLE
ReferenceError: wdio is not defined

### ISSUE THREAD

**Issue by medihack** [xolvio/meteor-webdriver#42]
When using this package with Mocha I get a "ReferenceError: wdio is not defined"  error under Meteor 1.2.0.2. I put the test file (your example in the Readme) under "tests/mocha/server/myTest.js". I also tried the client folder. Should I put it somewhere else?

```
ReferenceError: wdio is not defined
    at meteor://💻app/tests/mocha/server/testTest.js:5:1
    at wrappedFunc (meteor://💻app/packages/mike_mocha-core/packages/mike_mocha-core.js:125:1)
    at runWithEnvironment (meteor://💻app/packages/mike_mocha-core/packages/mike_mocha-core.js:43:1)
```

**Comment by samhatoum** [comment]
Hi

This package is not really being maintained anymore, it needs a lot of love!

I'll update the front page. Currently the way we do e2e testing is using meteor-cucumber and chimp. We'll be adding E2E to Jasmine in the medium term future

**Comment by medihack** [comment]
Thanks for the fast response. I am looking forward to the E2E Jasmine integration then.
